# Introduzione

Per importare i vari pacchetti uso il comando `import`, da ognuno di essi posso usare poi estrapolare le funzione che mi servono attraverso `from ... import ...`. 
Per estrapolarle tutte uso `from ... import *`.\
Se voglio avere informazioni allora posso usare il
[link](https://docs.python.org/3/library),
oppure usare la funzione di Py `print(dir(...))` per avere informazioni su un solo pacchetto. \
Se voglio avere informazioni sulla libreria [mathplot](https://matplotlib.org/stable/), devo andare sotto `Api Reference`.

In [2]:
import math
from math import sqrt
import scipy
import numpy as np

Non serve difinire prima il tipo delle variabili in Python, lui le definisce automaticamente quando le scrivi. 
La funzione `float` mi converte un numero che viene letto come una stringa in un effettivo numero

In [3]:
hello = "Hello, World!"
a=10
b="10"
c=float(b)
print(type(hello))
print(type(a))
print(b*3)
print(c*3)

<class 'str'>
<class 'int'>
101010
30.0


per definire l'output posso usare diversi comandi, sia per quanto riguarda la distanza di output, che le cifre significative. Devo sempre far seguire la varaibile dai **:**.
Il comando `:g` mi resituisce la formattazione migliore secondo il programma (solitamente 5 cifere significative).

In [4]:
t = 1.2345673245443
print(f"Default output gives t = {t}.")
print(f"We can set the precision: t = {t:.2}.")
print(f"Or control the number of decimals: t = {t:.2f}.")
print(f"We may set the space used for the output: t = {t:8.2f}.")
print(f"Best for Python: t = {t:g}")

Default output gives t = 1.2345673245443.
We can set the precision: t = 1.2.
Or control the number of decimals: t = 1.23.
We may set the space used for the output: t =     1.23.
Best for Python: t = 1.23457


### Funzioni Booleane

Utili sono le funzioni Booleane, che sono descritte da:

| **Operation** | **Meaning** |
| :--- | :---: |
|< |strictly less than|
| <= | less than or equal |
| > | strictly greater than |
| >= | greater than or equal |
| == | equal |
| != | not equal |
| is |  object identity |
| is not | negated object identity |

Queste posso concaternarle con i comandi `and`, `or`, `not`.

---

### Approfondimenti delle stringhe di testo


In [13]:
# è indifferente scrivere una stringa o con ' ' o con " "
'ciao'
"ciao"

Gatto = "Miao"


Gatto.upper() # Questo (.upper) è un metodo mi permette di rendere maiuscola tutta la parola senza riscriverla
print(Gatto.upper())

Gatto.lower() # Questo comando mi permette di rendere minuscola tutta la parola senza riscriverla
print(Gatto.lower())

print(Gatto.replace("o","a")) # Questo invece sostituisce la lettere/e della variabile

Manuele = "Grande Studioso"
print(Manuele.replace("Grande Studioso", "Studente")) # posso sostituire anche tutta la parola
print(Manuele.replace("o", "a",1)) # oppure scegliere quante volte sostituire la lettera

print(Manuele.split(" ")) #permette di separare le stringhe di testo

len(Manuele) #permette di contare il numero di caratteri di una stringa, spazi inclusi


MIAO
miao
Miaa
Studente
Grande Studiaso
['Grande', 'Studioso']


15

### Operazioni Matematiche


In [18]:
# se voglio ottenere un intero da una divisione:

c = 5 // 2 # dove approssima per difetto

# se voglio il resto di una divisione:
d = 5 % 2

print("La divisione fa", c, "con un resto di", d)

# posso dividere un numero con _ per renderlo più leggibile (senza che influisca sul risultato)
e = 1_000_000
print(e)

# per sommare un numero a se stesso posso usare:
x = 1 
x = x + 1
# oppure posso usare:
x += 1
print(x)

La divisione fa 2 con un resto di 1
1000000
3


In [26]:
tempi = [1.1, 2.0, 0.9, 1.5, 3.2, 0.8, 1.0]

# min(): Trova il valore più piccolo
print(f"Tempo minimo: {min(tempi)}")

# max(): Trova il valore più grande
print(f"Tempo massimo: {max(tempi)}")

# sum(): Somma tutti gli elementi
print(f"Somma totale dei tempi: {sum(tempi)}")

# sorted(): Crea una COPIA della lista ordinata (dal più piccolo)
print(f"Misure ordinate: {sorted(tempi)}")


Tempo minimo: 0.8
Tempo massimo: 3.2
Somma totale dei tempi: 10.5
Misure ordinate: [0.8, 0.9, 1.0, 1.1, 1.5, 2.0, 3.2]


## Funzioni utili

Sono funzioni utili la funzione:
* `help()`, che ti resituisce tutte le informazioni su una determinata funzione di un pacchetto
* `range(start,stop[,step])`, non comprende mai l'ultimo elemento (quello di stop)
* in un ciclo il comando `a += b` mi aggiunge ad un determinato numero una quantità, resistuendomi `a+b`

Assegnazione di un comando


In [5]:
# posso anche assegnare a una variabile il nome di una funzione
stampa = print 
stampa("Ciao") 

Ciao


Creazione di funzioni standard


In [10]:
#posso definire delle funzioni
def saluti(): #def sta per definire e saluti è la funzione che sto definendo
    print('Ciao') #dico cosa deve fare

saluti() #eseguo la funzione nuova

Ciao


In [27]:
L0 = 10.0   # Lunghezza iniziale
lam = 0.01  # Coefficiente lambda

def calcola_dilatazione():
    # Questa funzione è "cieca": cerca L0 e lam all'esterno.
    # Se cambiassimo nome alle variabili fuori non funzionerebbe
    L_finale = L0 * (1 + lam)

    # RETURN è fondamentale: restituisce il risultato al programma
    return L_finale

# La chiamo con le parentesi vuote () perché non accetta dati in ingresso
print(f"Lunghezza finale (fissa): {calcola_dilatazione()}")






# Ora definisco che la funzione DEVE ricevere due dati: L e coeff
def calcola_dilatazione(L, coeff):
    # Qui dentro uso i nomi generici L e coeff.
    # Non mi importa come si chiamano le variabili fuori.
    L_finale = L * (1 + coeff)
    return L_finale

# Posso passare le variabili esterne (L0, lam) dentro la funzione appena fatta
print(calcola_dilatazione(L0, lam))

# Oppure passo direttamente i numeri
print(f"Dilatazione Ferro: {calcola_dilatazione(4.0, 0.1)}")






# Posso anche definirli nella funzione
def calcola_dilatazione(L=5.0, coeff=0.1):
    L_finale = L * (1 + coeff)
    return L_finale

# CASO 1: Usa i default (5.0 e 0.1)
print(f"Standard: {calcola_dilatazione()}")

# CASO 2: Passo solo la lunghezza, Usa L=100 e coeff=0.1 (default)
print(f"Solo lunghezza: {calcola_dilatazione(L=100)}")

# CASO 3: Ignora i default e usa i miei dati
print(f"Tutto custom: {calcola_dilatazione(L=2.0, coeff=0.5)}")

Lunghezza finale (fissa): 10.1
10.1
Dilatazione Ferro: 4.4
Standard: 5.5
Solo lunghezza: 110.00000000000001
Tutto custom: 3.0


## Loops and List

### Loop

Quelli più semplici sono il `while` e `for` loop.\
Il `while` loop ha la seguente struttura:
```python:
while condition: 
    <statement 1> 
    <statement 2> 
    ... 
<first statement after loop>
```

Il `for` è meno generale, e si applica a soli elementi di una **lista**:
```python:
for element in list:
    <statement 1>
    <statement 2>
    ...
<first statement after loop>
```

Posso usare la funzione `for` in combinazione con `range` per creare una lista di elementi partendo da una determinata funzione iterattiva

In [6]:
P=100
r=5
N=10
amount=[]
for i in range(N+1):
    A= P* (1 + r/100)**i
    amount.append(A)
numeri= np.array(amount)
print(numeri.astype(int)) # converte tutto in numeri interi

[100 105 110 115 121 127 134 140 147 155 162]


### List
Le liste sono comode per creare delle concatenazioni di elementi; funzioni utili sono:
* `mylist[n]` per estrarre un elemento
* `mylist.append()` per aggiungere un elemento alla fine
* `del mylist[n]` per eliminare quell'elemento
* `a=b` crea la nuova variabile a che si riferisce a b, è un puntatore. 
* `a=b.copy()` crea una copia effettiva 

Se devo creare una lista di elementi posso usare la *list comprehension* ( `newlist = [expression for elemetns in the list]`) per scrivere in maniera più compatta.

In [7]:
P=100
r=5
r_1= 3
N=10
amounts = [P* (1 + r/100)**i for i in range(N+1)]
amounts_1 = [P* (1 + r_1/100)**i for i in range(N+1)]
numeri= np.array(amount)
print(numeri.astype(int))

[100 105 110 115 121 127 134 140 147 155 162]


La funzione `zip` mi aiuta ad organizzare meglio quando devo presentare elementi di più liste, inoltre mi estra automaticamente i valori.

In [8]:
for low, high in zip(amounts, amounts_1):
    print(int(low), int(high))

100 100
105 103
110 106
115 109
121 112
127 115
134 119
140 122
147 126
155 130
162 134


### Approfondimenti liste


In [23]:

lista = ['Nicolò', 'Carlo', 'Giulio']

lista.append('Luca') #aggiunge un elemento alla fine della lista
print(lista)

lista.remove('Giulio') #rimuove un elemento della lista
print(lista)

# posso controllare quanti elementi ho in una lista
print(len(lista))

# tuttavia nella lista si incomincia dal numero 0 quindi 0,1,2 e sono 3 elementi
print(lista[0]) #stampa il primo elemento della lista
print(lista[1]) #stampa il secondo elemento della lista

# Posso anche scegliere dove inserire gli elementi nella lista
lista.insert(1, 'Giulio')
print(lista)


lista.pop(1) #rimuove l'elemento in posizione 1
print(lista)

print(lista[1:2]) #  l'indice di "inizio" è incluso, quello di "fine" è ESCLUSO.


['Nicolò', 'Carlo', 'Giulio', 'Luca']
['Nicolò', 'Carlo', 'Luca']
3
Nicolò
Carlo
['Nicolò', 'Giulio', 'Carlo', 'Luca']
['Nicolò', 'Carlo', 'Luca']
['Carlo']


In [25]:
lavori = ['Fisico', 'Biologo', 'Cameriere']
Hobby = ['trekking', 'yoga', 'cucinare']

Attività = lavori + Hobby # Posso unire più liste

print(Attività[-1:]) #per l'ultimo elemento della lista
print(Attività[-2:]) #per gli ultimi 2 elementi della lista

['cucinare']
['yoga', 'cucinare']


### Some type

In [9]:
# list
# Sequence Type
# a collection of objects - mutable & ordered
['Ali','Xinyi','Miriam']

# tuple
# Sequence Type
# a collection of objects - immutable & ordered
('Thursday', 6, 9, 2018)

# set 
# a collection of unique objects - mutable & unordered
{'jack','sjoerd'}

# dict 
# Mapping Type
# mapping of key-value pairs
{'name':'DSAI', 'code':123,'credits':6}

# Use:
student = {"name": "Alice", "age": 20, "grade": "A"}
student_name = student["name"] # Access value by key.
print(student_name) # Alice
student["city"] = "New York" # Add new key-value pair.
print(student) 
student["age"] = 21 # Modify value by key.
print(student)
del student["grade"] # Remove key.
print(student)

Alice
{'name': 'Alice', 'age': 20, 'grade': 'A', 'city': 'New York'}
{'name': 'Alice', 'age': 21, 'grade': 'A', 'city': 'New York'}
{'name': 'Alice', 'age': 21, 'city': 'New York'}


## Librerie


### Pandas

In [38]:
#Importiamo la libreria assegnandole il soprannome 'pd'
# Pandas per esempio serve a manipolare tabelle di dati in modo veloce.
import pandas as pd

# Creiamo un file (possiamo pure caricarlo esternamente da excel)
dati_fisica = {
    'punto': ['A', 'B', 'C'],
    'raggio_r': [0.02, 0.05, 0.08],
    'carica_Q': [1e-6, 1e-6, 1e-6]
}

df_creato = pd.DataFrame(dati_fisica)
df_creato.to_csv('dati_fisica.csv', index=False) # Salviamo il file CSV


# Carichiamo un file esterno.
# read_csv() legge il file e lo trasforma in una tabella Python chiamata 'contenuti'.
# il file deve trovarsi nella stessa cartella del Suo script.
contenuti = pd.read_csv('dati_fisica.csv')

# Calcoliamo la somma di tutti i valori nella colonna 'Carica_Q'
carica_totale = contenuti['carica_Q'].sum()

print("Ecco i dati che abbiamo letto:")
print(contenuti)
print(f"La somma vettoriale delle cariche è: {carica_totale} µC")



ModuleNotFoundError: No module named 'pandas'

### Numpy


In [39]:
import numpy as np                      # Importa la libreria NumPy e la rinomina 'np'

# --- Generazione numeri casuali ---
c = np.random.randint(5000, 10000)      # Genera UN solo numero intero casuale tra 5000 (incluso) e 10000 (escluso)
print(c)                                # Stampa il numero

c = np.random.randint(5000, 10000, 10)  # Il terzo numero (10) indica QUANTI numeri generare: crea un array di 10 interi
print(c)

c = np.mean(c)                          # Calcola la media aritmetica dell'array creato sopra usando la funzione np.mean()
print(c)

# A differenza delle liste, gli array NumPy devono contenere dati dello stesso tipo
dati = np.array([1, 2, 3, 4, 5, 6])     # Trasforma una lista Python [..] in un array NumPy

media = dati.mean()                     # Calcola la media chiamando il metodo direttamente sulla variabile 'dati'

print(media)

a = dati * 2 # posso compiere anche operazioni matematiche
print(a)

9967
[7676 9816 6755 7837 8113 5334 6472 7831 6497 7512]
7384.3
3.5
[ 2  4  6  8 10 12]


### Matplotlib